# Generated by Django 3.0.2 on 2021-04-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_lists',
            name='last_man',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_lists',
            name='state',
            field=models.CharField(default='open', max_length=100),
            preserve_default=False,
        ),
    ]
