# Generated by Django 3.0.2 on 2021-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210412_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lists',
            name='image_url',
            field=models.CharField(max_length=8000000),
        ),
    ]
